### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by casshall** [ttricco/sarracen#38]
Minor syntax error in read_marisa:

In [1]: import sys
   ...: sys.path.append('/Users/cass/work/packages/sarracen/') # replace with your path to sarracen
   ...: 
   ...: import sarracen
   ...: 
   ...: sdf = sarracen.read_phantom('sg_00011')
   ...: 
   ...: #print(sdf)
   ...: 
   ...: #sdf.calc_density()
   ...: 
   ...: sdf.render('rho', xsec=0.0)
   ...: 
  File "/Users/cass/work/packages/sarracen/sarracen/readers/read_marisa.py", line 175
    def read_marisa(filename : str,
                             ^
SyntaxError: invalid syntax

**Comment by ttricco** [comment]
Strange. What version of Python are you using?

**Comment by ttricco** [comment]
Closing this issue. Please re-open if this is still a problem.
