### ISSUE TITLE
Missing features - Toomre parameter and 1D surface density plot

### ISSUE THREAD

**Issue by casshall** [ttricco/sarracen#40]
Hey there, this tool is really fantastic and I want to thank you all for what you are doing. Two suggestions - would be nice to plot Toomre Q and surface density profile in 1D

**Comment by ttricco** [comment]
Thanks for the suggestion. We're looking to better understand our user's scientific needs, so this is helpful. Though no promise on if/when calculation of either quantity will be implemented.
