### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by hlim88** [ttricco/sarracen#51]
This is more like minor issue rather than major. 

I was attempting to build `sarracen` in various places including my personal laptop and some HPC system. Most of cases are pretty straightforward to install but I got this error message from `pip install sarracen`:

```
ERROR: Could not find a version that satisfies the requirement sarracen (from versions: none)
ERROR: No matching distribution found for sarracen
```
It comes from one of the test machine doesn't have the requirements. The repo contains `requirements.txt` so it is easy to fix this issue like using `pip3 install -r requirements.txt` after cloning the repo. However, this procedure might not be obvious for light user or people who don't know python ecosystem well. So, I would suggest that to have more details install documentation and probably troubleshooting page can be helpful to install the tool.

**Comment by hlim88** [comment]
https://github.com/openjournals/joss-reviews/issues/5263

**Comment by ttricco** [comment]
@hlim88 Hi Hyun, I've added more documentation around installation to address your comments above and have closed this issue.
